import 'package:flutter/material.dart';

class Page2 extends StatelessWidget {
  const Page2({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: CustomScrollView(
      slivers: [
        SliverAppBar(
          floating: true,
        ),
        SliverList(
          delegate: SliverChildListDelegate(
            [
              Column(
                children: [
                  Text('ああああa'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('ああああa'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('ああああ12'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('あああああ'),
                  Text('いいいいい'),
                ],
              )
            ],
          ),
        ),
      ],
    ));
  }
}
